"""empty message

Revision ID: ff026256652a
Revises: 1193278ce0d8
Create Date: 2024-05-21 22:53:22.780627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff026256652a'
down_revision = '1193278ce0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trolley',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=800),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('price')

    op.drop_table('trolley')
    # ### end Alembic commands ###
